/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "HUM.h"
#include "HUM_aliases.h"
#include "Timeout.h"
#include "ClockTO.h"
#include "isr_Timeout.h"
#include "UART.h"
#include "LED_R.h"
#include "LED_R_aliases.h"
#include "LED_G.h"
#include "LED_G_aliases.h"
#include "LED_B.h"
#include "LED_B_aliases.h"
#include "PinWindCE.h"
#include "PinWindCE_aliases.h"
#include "PinWindRX.h"
#include "PinWindRX_aliases.h"
#include "ADC.h"
#include "Pin_Ubat.h"
#include "Pin_Ubat_aliases.h"
#include "Pin_Rain.h"
#include "Pin_Rain_aliases.h"
#include "Clock_1.h"
#include "isr_Rain.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "UART_IntClock.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

